payment (form_border_all)
  payment__header (form__item_space-v_l form__item_space-h_xl form__item_border_bottom)
    text (text_view_primary text_size_l, text_size_xxl) (l)
  payment__content (form__item_space-v_xxxl form__item_space-h_xl form__item_border_bottom)
    form__item (form__item_indent-b_xl form__item_distribute_between form__item_vertical-align_center)
      form__label (form__label_width_default)
        text (text_view_primary text_size_l) (l)
      input (input_size_l)
    form__item (form__item_indent-b_xl form__item_distribute_between form__item_vertical-align_center)
      form__label (form__label_width_default)
        text (text_view_primary text_size_l) (l)
      input (input_size_l)
  payment__footer (form__item_distribute_between form__item_border_bottom form__item_vertical-align_center form__item_space-v_l form__item_space-h_xl)
    text (text_view_primary text_size_l) (l)
    button (button_size_l)
