articles (list_view_default)
  articles__article (list__item_indent-b_xl)
    articles__unit (icon-plus icon-plus_vertical-align_center)
      articles__pic (theme_color_project-inverse icon-plus__icon icon-plus__icon_indent-r_m)
        image
      articles__content (icon-plus__block)
        text (text_view_secondary text_size_l) (m + s + s + m)
        text (text_view_primary text_size_l) (l + m)
        text (text_view_link text_size_m) (m + s)
  articles__article (list__item_indent-b_xl)
    articles__unit (icon-plus icon-plus_vertical-align_center)
      articles__pic (theme_color_project-inverse icon-plus__icon icon-plus__icon_indent-r_m)
        image
      articles__content (icon-plus__block)
        text (text_view_secondary text_size_l) (m + s + s + m)
        text (text_view_primary text_size_l) (l + m)
        text (text_view_link text_size_m) (m + s)
  articles__article (list__item_indent-b_xl)
    articles__unit (icon-plus icon-plus_vertical-align_center)
      articles__pic (theme_color_project-inverse icon-plus__icon icon-plus__icon_indent-r_m)
        image
      articles__content (icon-plus__block)
        text (text_view_secondary text_size_l) (m + s + s + m)
        text (text_view_primary text_size_l) (l + m)
        text (text_view_link text_size_m) (m + s)
