subscribtion (card_view_default theme theme_color_project-brand)
  subscribtion__info (card__content_space-a_xl)
    subscribtion__title
      text (text_view_primary text_size_xxl) (l)
    subscribtion__advantages (list)
      subscribtion__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (l + m + s)
      subscribtion__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (l + s + s)
      subscribtion__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (m + s + s)
      subscribtion__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (l + s + s)
      subscribtion__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (m + s + s)
  subscribtion__footer (card__footer_space-a_xl list)
    subscribtion__control (list__item_indent-b_s)
      input (input_size_l)
    subscribtion__control (list__item_indent-b_s)
      button (button_size_l button_width_full)
