subscription (card_view_default theme theme_color_project-brand)
  subscription__info (card__content_space-a_xl)
    subscription__title
      text (text_view_primary text_size_xxl) (l)
    subscription__advantages (list)
      subscription__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (l + m + s)
      subscription__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (l + s + s)
      subscription__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (m + s + s)
      subscription__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (l + s + s)
      subscription__advantage (list__item list__item_space-b_s)
        text (text_view_primary text_size_l) (m + s + s)
  subscription__footer (card__footer_space-a_xl list)
    subscription__control (list__item_indent-b_s)
      input (input_size_l)
    subscription__control (list__item_indent-b_s)
      button (button_size_l button_width_full)
